#!/bin/bash
DIR="${BASH_SOURCE%/*}";
if [[ -z "$@" ]]; then
  ARGS="-u 57110";
else
  ARGS="$@";
fi
if [[ -z "$SC_SYNTHDEF_PATH" ]]; then
  export SC_SYNTHDEF_PATH="$DIR/synthdefs/"
fi
export SC_PLUGIN_PATH="$DIR/plugins/";
exec "$DIR/bin/scsynth" $ARGS;